# Generated by Django 5.0.4 on 2024-04-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
